### ISSUE TITLE
停止容器后再开，怎么也启动不了了，上午还是没问题的

### ISSUE THREAD

**Issue by huchong05** [onlyLTY/oneKeyUpdate#53]
�2024-06-12T08:59:25.218832363Z 2024-06-12T16:59:25.218+08:00	 info 	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
�2024-06-12T08:59:25.219246893Z 2024-06-12T16:59:25.219+08:00	 error 	GetNewJwt error: Post "http://127.0.0.1:9123/api/auth": dial tcp 127.0.0.1:9123: connect: connection refused	caller=utiles/getImageList.go:17
�2024-06-12T08:59:25.219283964Z 2024-06-12T16:59:25.219+08:00	 error 	panic获取镜像列表出错: Post "http://127.0.0.1:9123/api/auth": dial tcp 127.0.0.1:9123: connect: connection refused	caller=zspace/dockercopilot.go:60
�2024-06-12T08:59:25.221356830Z panic: Post "http://127.0.0.1:9123/api/auth": dial tcp 127.0.0.1:9123: connect: connection refused
 2024-06-12T08:59:25.221375442Z 
62024-06-12T08:59:25.221381896Z goroutine 1 [running]:
+2024-06-12T08:59:25.221386750Z main.main()
i2024-06-12T08:59:25.221391695Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751

**Comment by huchong05** [comment]
问题解决了，虽然不知道为什么……就是把容器删掉，然后重新建一个……
