### ISSUE TITLE
极空间版本不能使用

### ISSUE THREAD

**Issue by hrbhht** [onlyLTY/oneKeyUpdate#77]
![image](https://github.com/user-attachments/assets/e626c60f-9949-45cc-a81f-93556e839c9e)
极空间拉取的版本，按作者的说明设置完，不断重启，看日志提示错误，如下：
2024-11-03T11:43:34.056747480Z 
2024-11-03T11:43:34.056752095Z goroutine 1 [running]:
2024-11-03T11:43:34.056755400Z main.main()
2024-11-03T11:43:34.056758329Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:44:34.514431362Z 2024-11-03T19:44:34.514+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:44:34.569212325Z 2024-11-03T19:44:34.569+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:44:34.569240690Z 2024-11-03T19:44:34.569+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:44:34.571391566Z panic: 请求错误，状态码:422
2024-11-03T11:44:34.571417115Z 
2024-11-03T11:44:34.571421925Z goroutine 1 [running]:
2024-11-03T11:44:34.571428261Z main.main()
2024-11-03T11:44:34.571431533Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:45:35.118104252Z 2024-11-03T19:45:35.117+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:45:35.183463902Z 2024-11-03T19:45:35.183+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:45:35.183495983Z 2024-11-03T19:45:35.183+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:45:35.185623257Z panic: 请求错误，状态码:422
2024-11-03T11:45:35.185645513Z 
2024-11-03T11:45:35.185649729Z goroutine 1 [running]:
2024-11-03T11:45:35.185652959Z main.main()
2024-11-03T11:45:35.185655845Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:46:35.679929399Z 2024-11-03T19:46:35.679+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:46:35.736458203Z 2024-11-03T19:46:35.736+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:46:35.736486512Z 2024-11-03T19:46:35.736+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:46:35.738734281Z panic: 请求错误，状态码:422
2024-11-03T11:46:35.738746443Z 
2024-11-03T11:46:35.738750930Z goroutine 1 [running]:
2024-11-03T11:46:35.738754774Z main.main()
2024-11-03T11:46:35.738758550Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:47:36.275106507Z 2024-11-03T19:47:36.274+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:47:36.335738129Z 2024-11-03T19:47:36.335+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:47:36.335763320Z 2024-11-03T19:47:36.335+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:47:36.337848269Z panic: 请求错误，状态码:422
2024-11-03T11:47:36.337863722Z 
2024-11-03T11:47:36.337868377Z goroutine 1 [running]:
2024-11-03T11:47:36.337871858Z main.main()
2024-11-03T11:47:36.337875020Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:48:36.904925004Z 2024-11-03T19:48:36.904+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:48:36.960267899Z 2024-11-03T19:48:36.960+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:48:36.960306206Z 2024-11-03T19:48:36.960+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:48:36.962641154Z panic: 请求错误，状态码:422
2024-11-03T11:48:36.962658020Z 
2024-11-03T11:48:36.962662372Z goroutine 1 [running]:
2024-11-03T11:48:36.962665765Z main.main()
2024-11-03T11:48:36.962668983Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:49:37.508859643Z 2024-11-03T19:49:37.508+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:49:37.572730386Z 2024-11-03T19:49:37.572+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:49:37.572769879Z 2024-11-03T19:49:37.572+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:49:37.574856820Z panic: 请求错误，状态码:422
2024-11-03T11:49:37.574872182Z 
2024-11-03T11:49:37.574876453Z goroutine 1 [running]:
2024-11-03T11:49:37.574879630Z main.main()
2024-11-03T11:49:37.574882729Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:50:38.187778476Z 2024-11-03T19:50:38.187+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:50:38.248222418Z 2024-11-03T19:50:38.248+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:50:38.248248761Z 2024-11-03T19:50:38.248+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:50:38.250312215Z panic: 请求错误，状态码:422
2024-11-03T11:50:38.250327827Z 
2024-11-03T11:50:38.250332839Z goroutine 1 [running]:
2024-11-03T11:50:38.250336089Z main.main()
2024-11-03T11:50:38.250339224Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:51:38.798676997Z 2024-11-03T19:51:38.798+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:51:38.859714775Z 2024-11-03T19:51:38.859+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:51:38.859748769Z 2024-11-03T19:51:38.859+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:51:38.861801061Z panic: 请求错误，状态码:422
2024-11-03T11:51:38.861821488Z 
2024-11-03T11:51:38.861843804Z goroutine 1 [running]:
2024-11-03T11:51:38.861851304Z main.main()
2024-11-03T11:51:38.861854561Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:52:39.355704605Z 2024-11-03T19:52:39.355+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:52:39.418748022Z 2024-11-03T19:52:39.418+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:52:39.418784896Z 2024-11-03T19:52:39.418+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:52:39.420884192Z panic: 请求错误，状态码:422
2024-11-03T11:52:39.420912301Z 
2024-11-03T11:52:39.420918213Z goroutine 1 [running]:
2024-11-03T11:52:39.420921956Z main.main()
2024-11-03T11:52:39.420925280Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:53:39.903918116Z 2024-11-03T19:53:39.903+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:53:39.965037374Z 2024-11-03T19:53:39.964+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:53:39.965063358Z 2024-11-03T19:53:39.964+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:53:39.967117203Z panic: 请求错误，状态码:422
2024-11-03T11:53:39.967129697Z 
2024-11-03T11:53:39.967134118Z goroutine 1 [running]:
2024-11-03T11:53:39.967137544Z main.main()
2024-11-03T11:53:39.967175856Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:54:40.572043280Z 2024-11-03T19:54:40.571+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:54:40.629007624Z 2024-11-03T19:54:40.628+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:54:40.629035513Z 2024-11-03T19:54:40.628+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:54:40.631260378Z panic: 请求错误，状态码:422
2024-11-03T11:54:40.631280199Z 
2024-11-03T11:54:40.631284559Z goroutine 1 [running]:
2024-11-03T11:54:40.631290367Z main.main()
2024-11-03T11:54:40.631293235Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-11-03T11:55:41.147847202Z 2024-11-03T19:55:41.147+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-11-03T11:55:41.207207802Z 2024-11-03T19:55:41.207+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-11-03T11:55:41.207235288Z 2024-11-03T19:55:41.207+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-11-03T11:55:41.209401723Z panic: 请求错误，状态码:422
2024-11-03T11:55:41.209426390Z 
2024-11-03T11:55:41.209438717Z goroutine 1 [running]:
2024-11-03T11:55:41.209442533Z main.main()
2024-11-03T11:55:41.209445904Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751

**Comment by onlyLTY** [comment]
环境变量的account需要填写极空间初始化时候的管理员账号。

**Comment by hrbhht** [comment]
谢谢，可以登录了，但是又出现都是最新的提示，我知道的有几个docker已经有新版本，docker copilot的版本已经更新到2.08了，请问这是怎么回事？谢谢

**Comment by onlyLTY** [comment]
> 谢谢，可以登录了，但是又出现都是最新的提示，我知道的有几个docker已经有新版本，docker copilot的版本已经更新到2.08了，请问这是怎么回事？谢谢

麻烦现在看看。检测更新需要点时间。如果依然全都是最新的话，麻烦重启下容器，然后然后等一分钟复制下日志。怀疑是网络问题
