### ISSUE TITLE
极空间升级后，容器无限重启。

### ISSUE THREAD

**Issue by exonerationem** [onlyLTY/oneKeyUpdate#82]
2024-12-30T10:20:42.032+08:00	 info 	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53

2024-12-30T10:20:42.032+08:00	 error 	GetNewJwt error: Post "http://127.0.0.1:9123/api/auth": dial tcp 127.0.0.1:9123: connect: connection refused	caller=utiles/getImageList.go:17

2024-12-30T10:20:42.032+08:00	 error 	panic获取镜像列表出错: Post "http://127.0.0.1:9123/api/auth": dial tcp 127.0.0.1:9123: connect: connection refused	caller=zspace/dockercopilot.go:60

panic: Post "http://127.0.0.1:9123/api/auth": dial tcp 127.0.0.1:9123: connect: connection refused

goroutine 1 [running]:

main.main()

	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x92e
全是这种报错

**Comment by Endygao** [comment]
我也遇到了同样的问题～

**Comment by for7GG** [comment]
先用绿联的，功能正常

**Comment by Endygao** [comment]
> 先用绿联的，功能正常

绿联版本在极空间上部署使用的话，环境配置要怎么改？我不太懂这个～

**Comment by onlyLTY** [comment]
感谢各位使用dc。近期极对docker功能进行了更新，已经在和极进行py交易，新的适配会在近期发出。如果着急使用，可以先ssh使用UGREEN版本创建

**Comment by gaoyoutan** [comment]
> > 先用绿联的，功能正常
> 
> 绿联版本在极空间上部署使用的话，环境配置要怎么改？我不太懂这个～

如何设置

**Comment by biubiushaka** [comment]
> 感谢各位使用dc。近期极对docker功能进行了更新，已经在和极进行py交易，新的装备会在近期发布。如果着急使用，可以先ssh使用UGREEN版本创建

还没PY好么？

**Comment by onlyLTY** [comment]
> > 感谢各位使用dc。近期极对docker功能进行了更新，已经在和极进行py交易，新的装备会在近期发布。如果着急使用，可以先ssh使用UGREEN版本创建
> 
> 还没PY好么？

得等极空间发版

**Comment by lclichen** [comment]
> > > 感谢各位使用dc。近期极对docker功能进行了更新，已经在和极进行py交易，新的装备会在近期发布。如果着急使用，可以先ssh使用UGREEN版本创建
> > 
> > 
> > 还没PY好么？
> 
> 得等极空间发版

发版是指他们在灰度吗（我这边今天收到了升级的推送）（然后就出问题了）

**Comment by yesugao** [comment]
每天来都来看看大佬跟进好了没，大佬的这个容器现在用不上，我的心灵很没有安全感。

**Comment by gexiaosen** [comment]
大佬，有动静吗

**Comment by onlyLTY** [comment]
> 大佬，有动静吗

刚去问了。快了。

**Comment by chenqimiao** [comment]
插眼

**Comment by onlyLTY** [comment]
最新消息同步。需要等极空间的compose功能上线，然后使用compose创建

**Comment by sabersang** [comment]
大佬，请问预计极空间的compose功能近期会上线吗

**Comment by onlyLTY** [comment]
极空间外测已上线compose部署。可以通过compose部署，已更新md，可以参照部署

**Comment by yesugao** [comment]
非常感谢老哥的付出，等不及极空间了，极空间Z4PRO性能版 已挂闲鱼。我换飞牛了，在飞牛也是使用老哥的容器，真的太棒了。
